server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/inventory
    username: postgres
    password:
  redis:
    host: localhost
    port: 6379
    ##密码，我这里没有设置，所以不填
    password:
    ## 设置最大连接数，0为无限
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cs237.kafkajava.controller
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
    controller: info
